// Fill out your copyright notice in the Description page of Project Settings.

#pragma once //Only include header once preventative measure

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Item.generated.h" //Autogenerated

UCLASS() //Reflection system
class BP_SLASH_API AItem : public AActor
{
	GENERATED_BODY() //Reflection System, Work with BP too
	
public:	
	AItem();
	virtual void Tick(float DeltaTime) override;
protected:
	virtual void BeginPlay() override;

private:
	float RunningTime;
	float Amplitude = 0.25f;
	float TimeConstant = 5.f;
};
